server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        min-idle: 0
    database: 0


oauth:
  loginPage: /auth/login
  loginProcessingUrl: /auth/authorize
